name: merkle-tree
version: 0.1.0.0
github: "gsebil08/merkle-tree"
license: BSD3
author: "Gauthier SEBILLE"
maintainer: "gauthier.sebille@gmail.com"
copyright: "2019 GSE"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/gsebil08/merkle-tree#readme>

dependencies:
  - base >= 4.7 && < 5
  - cryptonite
  - bytestring
  - text
  - memory
  - relude
  - hexstring

default-extensions:
  - NoImplicitPrelude
  - ScopedTypeVariables
  - OverloadedStrings

library:
  source-dirs: src

executables:
  merkle-tree-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -fprint-potential-instances
    dependencies:
      - merkle-tree

tests:
  merkle-tree-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      # Our test convention for HUnit would make it unnecessarily verbose to add the signature of each test
      - -fno-warn-missing-signatures
      # Sometimes you want to assert a pattern in tests
      - -fno-warn-incomplete-uni-patterns
      - -fprint-potential-instances
    dependencies:
      - merkle-tree
      - cryptonite
      # Unit testing
      - hspec